### ISSUE TITLE
Baby hoglins cause server crash when colliding/dying

### ISSUE THREAD

**Issue by chorbintime** [izofar/bygone-nether#25] opened 2023-05-31 06:30 UTC
### Describe the Bug

When a baby hoglin dies by fall damage or fire, it causes a server crash. 

### Reproduction Steps

1. Summon a baby hoglin near fire or a large drop
2. Watch the hoglin die
3. The server crashes
...

### Expected Result

The hoglin dies and drops its loot, without a crash occuring

### Crash Report or Log

https://mclo.gs/xHEzc14

### Operating System

Linux 

### Mod Version

1.2.1

### Minecraft Version

1.19.2

### Forge Version

Fabric Loader 0.14.19

### Other Mods

https://www.curseforge.com/minecraft/modpacks/curiosities-the-sequel

**Comment by izofar** [comment] 2023-09-12 23:07
Could not reproduce, and looking at the error log, there are a ton of mixins from other mods in the stack trace, none of them from this mod. In addition, I do not modify the ticking of hoglins. I conclude this very likely isn't an issue with Bygone Nether

**Comment by izofar** [comment] 2023-09-12 23:46
Correction: could reproduce when the death was not player-caused. This is due to a bug in porting lib that was fixed, but not in the embedding of the mod. Will fix

**Comment by izofar** [comment] 2023-09-16 21:02
Fixed in [eb5881b](https://github.com/izofar/bygone-nether/commit/eb5881bc8fd9d6573a8b8e52827f15bdb2e70922)

**Closed as completed by izofar** 2023-09-16 21:02 UTC
Labels: bug, 1.19.2, crash, fabric
